-- Create database structure and relationship tables
CREATE TABLE IF NOT EXISTS Users (
    USER_ID SERIAL PRIMARY KEY,
    USERNAME VARCHAR(20) UNIQUE NOT NULL,
    FIRSTNAME VARCHAR(25) NOT NULL,
    LASTNAME VARCHAR(25) NOT NULL,
    EMAIL VARCHAR(50) UNIQUE NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    USER_PICTURES BYTEA
);

CREATE TABLE IF NOT EXISTS  Roles (
    ROLE_ID SERIAL PRIMARY KEY,
    ROLE_NAME VARCHAR(20) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS UserRoles (
    USER_ID INT,
    ROLE_ID INT,
    PRIMARY KEY (USER_ID, ROLE_ID),
    FOREIGN KEY (USER_ID) REFERENCES Users(USER_ID),
    FOREIGN KEY (ROLE_ID) REFERENCES Roles(ROLE_ID)
);

CREATE TYPE publication_status AS ENUM ('Draft', 'Under Review', 'Published', 'Rejected');

CREATE TABLE IF NOT EXISTS POST (
    POST_ID SERIAL PRIMARY KEY,
    TITLE VARCHAR(50) NOT NULL,
    SUBTITLE VARCHAR(50) NOT NULL,
    CONTENT TEXT NOT NULL,
    POST_IMAGE BYTEA,
    TAG_LIST VARCHAR(100),
    USER_ID INT,
    FOREIGN KEY (USER_ID) REFERENCES Users(USER_ID),
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PUBLISHED_DATE TIMESTAMP DEFAULT NULL,
    PUBLICATION_STATUS publication_status DEFAULT 'Draft',
    LIKE_COUNTER INT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS COMMENT (
    COMMENT_ID SERIAL PRIMARY KEY,
    USER_ID INT,
    FOREIGN KEY (USER_ID) REFERENCES Users(USER_ID),
    POST_ID INT,
    FOREIGN KEY (POST_ID) REFERENCES POST(POST_ID),
    COMMENT_TEXT TEXT NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    VISIBILITY BOOLEAN DEFAULT TRUE,
    LIKE_COUNTER INT DEFAULT 0,
    DISLIKE_COUNTER INT DEFAULT 0
);

-- Create table for save tags
CREATE TABLE post_tags (
    post_id INT NOT NULL,
    tag VARCHAR(255) NOT NULL,
    CONSTRAINT fk_post
    FOREIGN KEY(post_id)
    REFERENCES post(post_id)
    ON DELETE CASCADE
);
